# Cross-compile KLINIKAL's Windows x86 demo from Linux with LLVM/Clang 22.
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86)
set(CMAKE_C_COMPILER_TARGET i686-pc-windows-msvc)
set(CMAKE_CXX_COMPILER_TARGET i686-pc-windows-msvc)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CLANG_BIN_DIR /usr/bin CACHE PATH "LLVM binary directory")
set(CMAKE_C_COMPILER "${CLANG_BIN_DIR}/clang-cl-22")
set(CMAKE_CXX_COMPILER "${CLANG_BIN_DIR}/clang-cl-22")
set(CMAKE_RC_COMPILER "${CLANG_BIN_DIR}/llvm-rc-22")
set(CMAKE_LINKER "${CLANG_BIN_DIR}/lld-link-22")
set(CMAKE_AR "${CLANG_BIN_DIR}/llvm-lib-22")

set(WINDOWS_TOOLCHAIN_ROOT /opt/wdk CACHE PATH "vsdownload.py destination")
file(GLOB MSVC_DIRS "${WINDOWS_TOOLCHAIN_ROOT}/VC/Tools/MSVC/*")
list(SORT MSVC_DIRS COMPARE NATURAL ORDER DESCENDING)
list(GET MSVC_DIRS 0 MSVC_BASE)
file(GLOB WINSDK_DIRS "${WINDOWS_TOOLCHAIN_ROOT}/WindowsKits/10/Include/*")
list(SORT WINSDK_DIRS COMPARE NATURAL ORDER DESCENDING)
list(GET WINSDK_DIRS 0 WINSDK_INCLUDE)
file(GLOB WINSDK_LIB_DIRS "${WINDOWS_TOOLCHAIN_ROOT}/WindowsKits/10/Lib/*")
list(SORT WINSDK_LIB_DIRS COMPARE NATURAL ORDER DESCENDING)
list(GET WINSDK_LIB_DIRS 0 WINSDK_LIB)

if(NOT IS_DIRECTORY "${MSVC_BASE}/include" OR
   NOT IS_DIRECTORY "${WINSDK_INCLUDE}/um" OR
   NOT IS_DIRECTORY "${WINSDK_LIB}/um/x86")
    message(FATAL_ERROR "vsdownload.py did not produce an MSVC x86 + Windows SDK layout")
endif()

set(WINDOWS_INCLUDE_FLAGS
    -imsvc "${MSVC_BASE}/include"
    -imsvc "${WINSDK_INCLUDE}/ucrt"
    -imsvc "${WINSDK_INCLUDE}/shared"
    -imsvc "${WINSDK_INCLUDE}/um"
    -imsvc "${WINSDK_INCLUDE}/winrt")
string(REPLACE ";" " " WINDOWS_INCLUDE_FLAGS "${WINDOWS_INCLUDE_FLAGS}")
set(CMAKE_C_FLAGS_INIT "${WINDOWS_INCLUDE_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_INIT "${WINDOWS_INCLUDE_FLAGS}" CACHE STRING "" FORCE)

set(WINDOWS_LINK_FLAGS
    "/libpath:${MSVC_BASE}/lib/x86"
    "/libpath:${WINSDK_LIB}/ucrt/x86"
    "/libpath:${WINSDK_LIB}/um/x86")
string(REPLACE ";" " " WINDOWS_LINK_FLAGS "${WINDOWS_LINK_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${WINDOWS_LINK_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${WINDOWS_LINK_FLAGS}" CACHE STRING "" FORCE)
